let cities = [
  "Abidjan",
  "Abu Dhabi",
  "Accra",
  "Addis Ababa",
  "Adelaide",
  "Ahmedabad",
  "Albuquerque",
  "Aleppo",
  "Alexandria",
  "Algiers",
  "Almaty",
  "Amman",
  "Amsterdam",
  "Ankara",
  "Antananarivo",
  "Apex",
  "Athens",
  "Atlanta",
  "Auckland",
  "Austin",
  "Bacău",
  "Baku",
  "Baltimore",
  "Bangalore",
  "Bangkok",
  "Barcelona",
  "Beijing",
  "Belfast",
  "Belgrade",
  "Belo Horizonte",
  "Bengaluru",
  "Berlin",
  "Bhopal",
  "Birmingham",
  "Bogotá",
  "Boston",
  "Brasília",
  "Brisbane",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Buffalo",
  "Cairo",
  "Calgary",
  "Cape Town",
  "Caracas",
  "Casablanca",
  "Chandigarh",
  "Chennai",
  "Chicago",
  "Chisinau",
  "Chongqing",
  "Cincinnati",
  "Cleveland",
  "Cologne",
  "Colombo",
  "Colorado Springs",
  "Columbus",
  "Copenhagen",
  "Curitiba",
  "Dakar",
  "Dallas",
  "Dar es Salaam",
  "Delhi",
  "Denver",
  "Detroit",
  "Dhaka",
  "Doha",
  "Dubai",
  "Dublin",
  "Durban",
  "Düsseldorf",
  "Edmonton",
  "Faisalabad",
  "Fort Worth",
  "Frankfurt",
  "Fresno",
  "Fukuoka",
  "Gaborone",
  "Gdańsk",
  "Geneva",
  "Genoa",
  "George Town",
  "Gothenburg",
  "Guadalajara",
  "Guangzhou",
  "Gurgaon",
  "Gurugram",
  "Hamburg",
  "Hangzhou",
  "Hanoi",
  "Harare",
  "Hartford",
  "Helsinki",
  "Ho Chi Minh City",
  "Hong Kong",
  "Honolulu",
  "Houston",
  "Hyderabad",
  "Indianapolis",
  "Islamabad",
  "Istanbul",
  "Jacksonville",
  "Jaipur",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Johannesburg",
  "Kabul",
  "Kampala",
  "Kansas City",
  "Karachi",
  "Kathmandu",
  "Kiev",
  "Kingston",
  "Kinshasa",
  "Kolkata",
  "Kuala Lumpur",
  "Kuwait City",
  "Kyoto",
  "Lagos",
  "Lahore",
  "Las Vegas",
  "Leeds",
  "Leicester",
  "Leon",
  "Lilongwe",
  "Lima",
  "Lisbon",
  "Liverpool",
  "Ljubljana",
  "Ljubljana",
  "London",
  "Los Angeles",
  "Louisville",
  "Lucknow",
  "Luxembourg City",
  "Lyon",
  "Macao",
  "Madison",
  "Madrid",
  "Manama",
  "Manaus",
  "Manchester",
  "Manila",
  "Marrakech",
  "Melbourne",
  "Memphis",
  "Mexico City",
  "Miami",
  "Milan",
  "Milwaukee",
  "Minneapolis",
  "Minsk",
  "Montevideo",
  "Montreal",
  "Moscow",
  "Mumbai",
  "Munich",
  "Nairobi",
  "Naples",
  "Nashville",
  "New Delhi",
  "New Orleans",
  "New York City",
  "Newcastle",
  "Nice",
  "Nicosia",
  "Nizhny Novgorod",
  "Noida",
  "Norfolk",
  "Norrköping",
  "Northampton",
  "Nottingham",
  "Nuremberg",
  "Oakland",
  "Oklahoma City",
  "Omaha",
  "Orlando",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Panama City",
  "Paris",
  "Patna",
  "Perth",
  "Philadelphia",
  "Phoenix",
  "Pittsburgh",
  "Portland",
  "Porto",
  "Porto Alegre",
  "Prague",
  "Pretoria",
  "Pune",
  "Qingdao",
  "Quebec City",
  "Quito",
  "Raleigh",
  "Rangoon",
  "Recife",
  "Rennes",
  "Riga",
  "Rio de Janeiro",
  "Riyadh",
  "Rome",
  "Rosario",
  "Rotterdam",
  "Saint Petersburg",
  "Salt Lake City",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "San Salvador",
  "Sana'a",
  "Santa Cruz",
  "Santa Cruz de la Sierra",
  "Santa Fe",
  "Santiago",
  "Santo Domingo",
  "São Paulo",
  "Seattle",
  "Seoul",
  "Shanghai",
  "Shenzhen",
  "Singapore",
  "Sofia",
  "St. Louis",
  "Stockholm",
  "Stuttgart",
  "Surabaya",
  "Surat",
  "Sydney",
  "Tampa",
  "Tashkent",
  "Tbilisi",
  "Tehran",
  "Tel Aviv",
  "The Hague",
  "Thimphu",
  "Tianjin",
  "Tijuana",
  "Tokyo",
  "Toronto",
  "Tripoli",
  "Tucson",
  "Tulsa",
  "Turin",
  "Ulaanbaatar",
  "Uppsala",
  "Utrecht",
  "Valencia",
  "Vancouver",
  "Vienna",
  "Vientiane",
  "Vilnius",
  "Virginia Beach",
  "Warsaw",
  "Washington",
  "Wellington",
  "Winnipeg",
  "Wuhan",
  "Wuxi",
  "Xi'an",
  "Xiamen",
  "Yerevan",
  "Zagreb",
  "Zhengzhou",
  "Zürich"
];
